apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db
    app: wordpress-app
spec:
  containers:
    - name: db
      image: mysql
      env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: aman
        - name: MYSQL_PASSWORD
          value: password
      ports:
        - containerPort: 3306
