apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db
    app: wordpress-app
spec:
  containers:
    - name: db
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
      ports:
        - containerPort: 3306
