apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
    app: wordpress-app
spec:
  type: ClusterIP
  selector:
    name: mysql
    app: wordpress-app
  ports:
   - targetPort: 3309
     port: 3309