apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    app: wordpress-app
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
      ports:
        - containerPort: 3309
